version: "3.8"

services:
  dorcas_base_hub:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - user=olawoye
        - uid=1000
    container_name: dorcas_base_hub
    working_dir: /var/www/dorcas-hub/
    env_file:
      - .env.docker
    volumes:
      - "./:/var/www/dorcas-hub"
    restart: unless-stopped

  dorcas_base_hub_web:
    restart: unless-stopped
    image: nginx:1.17-alpine
    ports:
      - "18033:80"
    container_name: dorcas_base_hub_web
    depends_on:
      - dorcas_base_hub
    volumes:
      - ./:/var/www/dorcas-hub
      - ./nginx/hub.conf:/etc/nginx/conf.d/default.conf

  dorcas_base_hub_mysql:
    container_name: dorcas_base_hub_mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "18034:3306"
    volumes:
      - dorcas_base_hub_database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Jns3jSHl1Ak
      - SERVICE_NAME=dorcas_base_hub_mysql

volumes:
  dorcas_base_hub_database:
    driver: local



networks:
  dorcas_base:
    driver: bridge